apiVersion: v1
kind: Pod
metadata:
  name: test-unsigned-image
  namespace: payments
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: test
      image: ghcr.io/raimadb/ledger-api@sha256:dbe15c9cef753607691b9c49d1b6aafbabf3b37613978e053414b7b47d5ef903
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
