---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgBhU/kMar/8NxfX8sr1+ZRt+2wORwHnZba0TIVsibGWMNocA5LTxxf4OTpo3G/m/mj86hwgmVsvC95sRPItu6m7l3C+W6+UFNYTGP9z7hlmPIQjcvIn9O4Yf6ZgBhryHtsYllNp1T9kJOOJKQOi4Mhb3f8X+ARqcB4V2lchseIGXeAymhw+kjeMcy4vkKAJFhDmTcGIjZRH4YI/k81yTyarvt6wZJk/fpbYD2AMV4ZRija+dFxMrD75oakSJ+dnmnpJqtF+s/nZl+6RfWFe6jUwmFwSx4eqpjOuz55QOnUUaIzIKbeSLhjn77bBnlcU3Rx6M+3fsp8pNWTWHXcm1y0Fo7Yu5wSLAosy4WaT/ieTONuDm3o7S76HHtWG62QsU9HtpCTH05tzqsu5cZ1SIv6xdfYZBW3G4+PQrDo7wWG8reIsWOJtI80CEKFn1JZHd5E+WIWyrE+WyA1FootE9whoqSfEiRcXw7DiPLKvgevYEAOwgOUocZt4/OGwhxElnbh9aUqhhTE0mgiqO1wrLGfH2P+VTPG7OrXlvmdsdHQYsHK/7kROgpo03+O1iCS2sRnBxIZVpaeWs3YS+juZ7IB0xGoSxEg5vx34FHaIpFLmG5XmmZydTMua1nUrFYGKjlT0dPyGrn9QswNEv02AUVEK+6K16DPbG7aGBU7g9zkeWc+PtyrZ5JG1uLAOoMJYR3809AjDSQocw0H07Q==
    STRIPE_API_KEY: AgAG+OuKgQwRSIe8/8xyqAsV8pZ4/EN8QBqA2US2XcpuRMblyyTaSw4Rj+OxN0zTDa58JA1KxfBQWFVYYLKovUdyNewJsi3/u2eg6qIeQEMG2KWIvg6b4ZBA4+N0pmzOqMKFLsvg2Vzi2mS9ewZxCuEnSkwdLX4VfsOvMJnmDmmkm/AQjYxzHpZh41mYocA9xetYcYVLjPSwToMnQ56PerkTl7p2lKnjtAWyhKa+IIqE4kfWh19QUm3XyWnUqhWDM3gqf0lPFDRbqfMOE7eTZqW+i8Toq7QVFLhz1VTbaGwUB99JACzGZmNn6a0cHzn6Y9szT0fGJpjkFeH+DSWbarm6S5g57vrCdALTlMEhbHBeji65Mva+92b2bNrIBzQrfLi9AMLTQfHZ/2uCH1oZ5YCwDZlF1rE8eVDbDqYz+3QHSxjlRs3Bj9eCZV6UOzVlmNNWLxvw6I85DyoT5kpD0jt2wZxtVMZicViAUvAvHvY4dXB8KTDumibsIx63qpbnyaLlQP0ip22UlnITiKdDXLXhQ95R208J1w21wxWI5M1DVjnetE9ay/GaDhJXacWgUMVwDVciInpQ9sV5Ej+usd7/k1BxTMEUBz10imOPn3Nj3UUMv9SZqggwdjJK73Po4+TMxUdFMugkHbzXz9Zxea/uvsmGFXCnzIbgcRKvw9J4dSbrzXHy7rnTKSwefZoaba9sDAWpMsS5YNqYSo2rgdpZjFMYvJxA/XbU54o0/g==
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
